#!/usr/bin/bash
#
# Put customizations to your image in this file.

VPNADM_VERSION='0.2'

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Munin plugins
MUNIN_PLUGINS="
	openvpn
"

# Exit if any commands fail
set -o errexit

echo "* Use default python 3.6"
pkg_alternatives manual python36

echo "* Configuring image specific packages."
mkdir -p /opt/vpnadm

echo "* Download and extract vpnadm to /opt/vpnadm"
curl -L "https://github.com/wiedi/vpnadm/archive/v${VPNADM_VERSION}.tar.gz" | gtar xz -C /opt/vpnadm --strip-components=1

echo "* Add vpnadm user"
groupadd vpnadm
useradd -d /opt/vpnadm -c "vpnadm user" -s /usr/bin/false -g vpnadm vpnadm

echo "* Setup permissions for vpnadm folder"
chown -R vpnadm:www /opt/vpnadm

echo "* Install missing dependencies via pip"
grep -v 'cryptography' /opt/vpnadm/requirements.txt > /tmp/requirements.txt
pip3.6 install -r /tmp/requirements.txt

echo "* Activate munin plugins"
/opt/core/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
